spring:
  #  main:
  #    allow-bean-definition-overriding: true
  application:
    # 应用名称
    name: service-webflux-consumer
  # 不启用ribbon-loadbalancer，这样就会用
  cloud:
    loadbalancer:
      retry:
        # 不用loadbalancer自带的retry，用我们自己的resilience4j的retry
        enabled: false
      ribbon:
        enabled: false
      cache:
        # 本地微服务实例列表缓存时间
        ttl: 1
        # 缓存大小，你的微服务调用多少个其他微服务，大小就设置为多少，默认256
        capacity: 256
server:
  port: 8202

# actuator设置
management:
  endpoint:
    health:
      # 对于Health接口，显示详情
      show-details: always
  endpoints:
    jmx:
      exposure:
        # jmx不暴露所有接口
        exclude: '*'
    web:
      exposure:
        # http暴露所有actuator接口
        include: '*'

eureka:
  client:
    # eureka client刷新本地缓存时间
    # 默认30s
    registry-fetch-interval-seconds: 5
    service-url:
      # 默认eureka集群, 这里一定不能用中划线，因为是map的key
      defaultZone: http://127.0.0.1:8211/eureka/
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    metadata-map:
      zone: zone1
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    # app名称，不填写在Spring-cloud-netflix体系下默认就是spring.application.name
    appname: ${spring.application.name}
    # 目前没啥卵用，可以用这个扩展一些功能
    #    app-group-name:
    # 主机名称，如果不填写，就通过org.springframework.cloud.commons.util.InetUtils从网卡读取，如果填写了，则会覆盖，并ip-address也需要设置
    #    hostname:
    # ip名称，如果不填写，就通过org.springframework.cloud.commons.util.InetUtils从网卡读取，如果填写了，则会覆盖，并hostname也需要设置
    #    ip-address:
    # 是否注册到Eureka就是UP的状态，如果标记为false，那么在注册到Eureka上面的时候就是Starting状态而不是UP状态，参考源码：`com.netflix.appinfo.providers.EurekaConfigBasedInstanceInfoProvider`
    # 之后我们会想到一个问题，就是什么时候才将
    instanceEnabledOnit: true
    non-secure-port: ${server.port}

feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 1000
      service-provider2:
        connectTimeout: 1000
        readTimeout: 8000

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 50
      minimumNumberOfCalls: 5
      slidingWindowType: TIME_BASED
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 30
      recordExceptions:
        - java.lang.Exception
